### ISSUE TITLE
fuck the bot

### ISSUE THREAD

**Issue by Shu-Junior** [thimble-bot/thimble-bot#11]
why cant i use bot

**Comment by jozsefsallai** [comment]
First of all, thanks but I'm not sexually attracted to robots. 

As for your question, I'm afraid you have to be a bit more specific on what your issue is if you want me to help you.

**Comment by Shu-Junior** [comment]
i need the thimbles game bot

**Comment by jozsefsallai** [comment]
Assuming you're talking about https://evoplay.games/game/thimbles/, this is not a Thimbles game bot, it's a Discord bot.
